-- ============================================================
-- Zephy & Zara: Island Stack - Supabase Database Schema
-- Run this script in the Supabase SQL Editor:
-- Supabase Dashboard -> SQL Editor -> New Query -> Paste & Run
-- ============================================================

-- 1. PROFILES TABLE (Stores player profile, device identity, and personal best stats)
CREATE TABLE IF NOT EXISTS public.profiles (
    id TEXT PRIMARY KEY,                             -- Device UUID / ID (e.g. 'player_xxx_yyy')
    name TEXT NOT NULL DEFAULT 'Guest Explorer',     -- Player display name
    username TEXT,                                   -- Alternative username field for compatibility
    character TEXT NOT NULL DEFAULT 'zephy',         -- Selected character ('zephy' or 'zara')
    best_score INTEGER NOT NULL DEFAULT 0,           -- Highest score achieved
    best_perfect INTEGER NOT NULL DEFAULT 0,         -- Most perfect landings in a single run
    best_jumps INTEGER NOT NULL DEFAULT 0,           -- Most total jumps in a single run
    best_combo INTEGER NOT NULL DEFAULT 0,           -- Longest combo streak
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 2. PLAYERS VIEW (Fallback alias for profiles table used in Stacked.html)
CREATE OR REPLACE VIEW public.players AS 
SELECT * FROM public.profiles;

-- 3. LEADERBOARD TABLE (Stores game run submissions and top scores)
CREATE TABLE IF NOT EXISTS public.leaderboard (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id TEXT,                                  -- References device/profile ID
    name TEXT NOT NULL,                              -- Player name at time of score
    character TEXT NOT NULL DEFAULT 'zephy',         -- 'zephy' or 'zara'
    score INTEGER NOT NULL DEFAULT 0,                -- Final score of run
    perfect INTEGER NOT NULL DEFAULT 0,              -- Count of perfect landings
    combo INTEGER NOT NULL DEFAULT 0,                -- Max combo achieved in run
    jumps INTEGER NOT NULL DEFAULT 0,                -- Total blocks successfully jumped
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- ============================================================
-- PERFORMANCE INDEXES
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_leaderboard_score ON public.leaderboard (score DESC);
CREATE INDEX IF NOT EXISTS idx_leaderboard_player_id ON public.leaderboard (player_id);
CREATE INDEX IF NOT EXISTS idx_leaderboard_created_at ON public.leaderboard (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_profiles_best_score ON public.profiles (best_score DESC);

-- ============================================================
-- AUTOMATIC TIMESTAMP TRIGGER (Updates updated_at on profile edit)
-- ============================================================
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_profiles_updated_at ON public.profiles;
CREATE TRIGGER set_profiles_updated_at
    BEFORE UPDATE ON public.profiles
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- ============================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- Since the frontend uses the public/anon key without auth login,
-- public access policies must be granted so the game can read/write data.
-- ============================================================

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leaderboard ENABLE ROW LEVEL SECURITY;

-- Clean up any existing policies to avoid duplicates
DROP POLICY IF EXISTS "Public can view profiles" ON public.profiles;
DROP POLICY IF EXISTS "Public can insert profiles" ON public.profiles;
DROP POLICY IF EXISTS "Public can update profiles" ON public.profiles;
DROP POLICY IF EXISTS "Public can view leaderboard" ON public.leaderboard;
DROP POLICY IF EXISTS "Public can insert leaderboard" ON public.leaderboard;

-- Profiles Policies (Read, Insert, Update)
CREATE POLICY "Public can view profiles"
    ON public.profiles FOR SELECT
    TO anon, authenticated
    USING (true);

CREATE POLICY "Public can insert profiles"
    ON public.profiles FOR INSERT
    TO anon, authenticated
    WITH CHECK (true);

CREATE POLICY "Public can update profiles"
    ON public.profiles FOR UPDATE
    TO anon, authenticated
    USING (true)
    WITH CHECK (true);

-- Leaderboard Policies (Read, Insert)
CREATE POLICY "Public can view leaderboard"
    ON public.leaderboard FOR SELECT
    TO anon, authenticated
    USING (true);

CREATE POLICY "Public can insert leaderboard"
    ON public.leaderboard FOR INSERT
    TO anon, authenticated
    WITH CHECK (true);

-- ============================================================
-- REALTIME SUBSCRIPTIONS (Optional: enables live leaderboard updates)
-- ============================================================
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'leaderboard'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.leaderboard;
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'profiles'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.profiles;
    END IF;
END $$;
